### ISSUE TITLE
"Workspaces 2.0" from Chrome v.63: *.js modified in external editor does not update

### ISSUE THREAD

**Issue by Gennady-G** [tavikukko/Chrome-SP-Editor#30]
Greetings @tavikukko !

![2017-12-18_163324](https://user-images.githubusercontent.com/5569346/34110990-f9686da2-e410-11e7-9b66-6e4c07598c0f.png)

![2017-12-18_160414](https://user-images.githubusercontent.com/5569346/34110211-a2f2fc96-e40e-11e7-8865-e6dc8a17332a.png)

Looks like something was updated from Chrome Dev Tools side, please note "Filesystem" tab. Now js source is updated only if I hit Ctrl+S in dev tools "Source" window(added red label). 

"Ctrl+S" in external editor does not affect

![2017-12-18_161543](https://user-images.githubusercontent.com/5569346/34110317-f2196760-e40e-11e7-8b54-575e54bfcbeb.png)

Can You test please?

**Comment by tavikukko** [comment]
Thanks @Gennady-G, I will have a look later today.

**Comment by tavikukko** [comment]
This is not cool, they have changed the way the API reacts to changes in localmodications... any ideas anybody? Its no longer triggering the [onResourceContentCommitted](https://developers.chrome.com/extensions/devtools_inspectedWindow#event-onResourceContentCommitted) thou the file is updated in the sources pane..

**Comment by Gennady-G** [comment]
> they have changed the way the API reacts to changes in localmodications... 

// offtop:
Weeeird...

**Comment by tavikukko** [comment]
ok, I hope its a bug in Chrome. Seems that the mapping to local resource does not work.
[chromium bugs](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=Workspace&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids)

**Comment by tavikukko** [comment]
wiiierd, i just got it working.. and then it didn't work anymore.. and I do not have any idea what i did 🗡 I will keep on digging..

**Comment by Gennady-G** [comment]
Well it still works if edit and save direct in "Sources" tab.. Maybe You saved there?..

Voted for bug. Hope they will fix it, it should be something with their "Workspaces"

**Comment by Gennady-G** [comment]
..WORKS!?))

**Comment by tavikukko** [comment]
I got it working again :) in both, sources and from vs code. But again, cannot reproduce. The thing is, when you see "green ball" next to the file icon, the mapping is correct and then everything work as it should.

**Comment by Gennady-G** [comment]
Yes, green bal is something new, haven't seen it before:

![2017-12-18_223108](https://user-images.githubusercontent.com/5569346/34126667-10496666-e443-11e7-9c4f-c4589b89b1da.png)

Great news! :)

**Comment by tavikukko** [comment]
well, if you see that, it should work now. how do you get that green thing?

**Comment by Gennady-G** [comment]
Don't know :)

Maybe they are changing something right now?..
js works, but I still can't get same green ball for css

**Comment by tavikukko** [comment]
whats your chrome version, I got:
Version 63.0.3239.108 (Official Build) (64-bit)
And I cant get that mapping working, no "green balls"..

**Comment by Gennady-G** [comment]
Same
63.0.3239.108 (Official, 64bit)

Same for me. I played with Devtools-> 'Sources' settings, now I can't get green ball even for js file..

![2017-12-18_225008](https://user-images.githubusercontent.com/5569346/34127431-cc713786-e445-11e7-8704-f2d3ce4fb0e7.png)

Think we need to wait, maybe it is DevTools bug..

Thank You much @tavikukko !

**Comment by pkreipke** [comment]
Hmm, I'm not able to save but I don't even see any trace of the attempt in the console. So maybe only slightly related.

I'm on Mac and I'm wondering if it's a key mapping problem: Ctrl-D also doesn't execute the PnP sample - instead it functions like a backspace keypress.

**Comment by tavikukko** [comment]
@pkreipke try Cmd-D if you are on macOs

**Comment by pkreipke** [comment]
Nothing in console, no change to file in SP. 

Note: SP is 2013 on-premise.

**Comment by pkreipke** [comment]
Chrome Dev tools shortcuts - I see Command+D in use but no Ctrl-D. 

https://developers.google.com/web/tools/chrome-devtools/shortcuts

I'm eager to try your extension - how can I help debug?

**Comment by pkreipke** [comment]
I'm an idiot: 
- Command+S saved to SP from sp-editor 
- Command+D ran the PnP snippet!

Per

**Comment by tavikukko** [comment]
@Gennady-G ok, I got it working :) finally! So, the file have to match (local and remote) with the content AND when you have opened the file in sources tab, hit Refresh (F5), then it will get the green dot and the save work again. But if the files are not in sync, then it will map it. Could you test? Thanks.

**Comment by Gennady-G** [comment]
Hi @tavikukko !

I've tried briefly, but cannot get this green ball hitting f5.. Think I used f5 in previous version too, it "catches" file after refresh

I tried earlier today, using folders with no spaces (I put sources in "_catalogs" istead of "Style%20Library"), but no luck. I'll continue tomorrow.

upd.: There are a lot of bugs about mappings, look: [chromium bugs](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=Workspace&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids)

**Comment by tavikukko** [comment]
@Gennady-G any update on this? I can successfully update from VS Code using SP Editor. Chrome will now automatically bind the files if the filename AND content matches.

**Comment by Gennady-G** [comment]
Hi @tavikukko !

Problem is still actual for me. Reviewed some bugreports on DevTools board([thread](https://bugs.chromium.org/p/chromium/issues/detail?id=794946&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=)). There is a message:

> 1. Note: workspaces now work only for localhost:// domains. To work with real websites, please use "network overrides" feature: https://umaar.com/dev-tips/162-network-overrides/

Tried this "[Network overrides](https://umaar.com/dev-tips/162-network-overrides/)" from 'DevTools Experiments', but don't see this setting in "Experiments settings":

![2018-01-08_132458](https://user-images.githubusercontent.com/5569346/34665450-9c692fd2-f479-11e7-96a0-5578d3362550.png)

If I edit source in 'Sources panel' and hit ctrl+s -it succesfully saves to SharePoint
If I edit file in external editor - it shows changes in sources panel, but does not sync with SharePoint

p.s.: I am not alone, hehe) People are a little angry with this Chrome workspaces "improvement":

![2018-01-08_135944](https://user-images.githubusercontent.com/5569346/34666220-a880d9e8-f47c-11e7-9b9a-1805ce5e8a87.png)

**Comment by tavikukko** [comment]
thanks @Gennady-G for the update.
I can't get this thing working anymore...so lets see. Looks like they have changed something big time..  I also tried to use the experiences thingy but could not succeed. Lets stay tuned.

**Comment by tavikukko** [comment]
@Gennady-G quess what , got it working with Canary and these steps https://stackoverflow.com/a/41192461
<img width="314" alt="screen shot 2018-01-08 at 19 47 38" src="https://user-images.githubusercontent.com/2223355/34684152-e269ca40-f4ac-11e7-9b19-6345d6198ced.png">

<img width="494" alt="screen shot 2018-01-08 at 19 47 15" src="https://user-images.githubusercontent.com/2223355/34684192-f46ab9f2-f4ac-11e7-8313-8cf43b55c484.png">

**Comment by Gennady-G** [comment]
I can enable DevTools experiments, but cannot see "Persistence 2.0" on my version after restart:

![2018-01-09_202659](https://user-images.githubusercontent.com/5569346/34736463-ac2ddf0a-f57b-11e7-8e21-53b061ab274b.png)

Tried with Chrome:

![2018-01-09_202555](https://user-images.githubusercontent.com/5569346/34736482-c047a99e-f57b-11e7-8096-895a54bb3cc5.png)

and Canary:

![2018-01-09_201553](https://user-images.githubusercontent.com/5569346/34736500-cf8c70a6-f57b-11e7-9b1f-6ee2b73b547a.png)

But it is very good news that You found solution for Your version!) That is 50% success
I'll keep You posted

**Comment by tavikukko** [comment]
@Gennady-G use the "override requests with workspace project"
<img width="556" alt="screen shot 2018-01-09 at 22 44 10" src="https://user-images.githubusercontent.com/2223355/34742415-c91b099a-f58e-11e7-9da9-695f2a1f1c4f.png">

**Comment by Gennady-G** [comment]
Hi @tavikukko !

I've already tried this option before. Tried second time, and also enabled all these checkboxes:

![2018-01-10_143937](https://user-images.githubusercontent.com/5569346/34768526-7c5edf06-f614-11e7-87d2-f513b34e9166.png)

I don't see "Override" option in context menu on Win 2012. Maybe my server OS causes problems

![2018-01-10_143927](https://user-images.githubusercontent.com/5569346/34768550-9230079c-f614-11e7-92fc-674fff04922b.png)

**Comment by tavikukko** [comment]
@Gennady-G you are almost there. Can you see Overrides Tabs on Sources? if you can, you need to click the "+Setup overrides" and select folder. After that you will be see the "Save for overrides" option in network context menu.

**Comment by tavikukko** [comment]
Just tested with Win10 + Canary and all good. Remember to relaunch DevTools after enabling “override requests with workspace project” in experiences.

**Comment by Gennady-G** [comment]
Arghhh!...

There is "Override **tab**"...

YES :)

Thank You @tavikukko very very much! It works! :) This workaround creates subfolder in target directory, so we need to re-open new file in external editor.

![2018-01-11_131749](https://user-images.githubusercontent.com/5569346/34817736-33126d0e-f6d2-11e7-9d5b-530c5f783076.png)

Thank You much for Your time, You saved me))

Best regards,  
Gennady

**Comment by tavikukko** [comment]
I will write instructions for this workaround and then close this. thanks @Gennady-G for reporting and helping solving the issue!

**Comment by Gennady-G** [comment]
> and then close this. 

Yeah!) Till next time DevTools developers break something else :-D

**Comment by tavikukko** [comment]
closing, open is still an issua.
